apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-secrets
  namespace: flux-system
spec:
  sourceRef:
    kind: Bucket
    name: flux
  path: ./manifests/configurations/secrets/local
  prune: true
  wait: true
  interval: 10s
  timeout: 2m
  retryInterval: 3m
  dependsOn:
    - name: infra-secrets
  postBuild:
    substitute:
      secrets_hostname: secrets.cloud.test
