apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-secrets
  namespace: flux-system
spec:
  sourceRef:
    kind: Bucket
    name: flux
  path: ./manifests/infrastructure/secrets/local
  prune: true
  wait: true
  interval: 10s
  timeout: 2m
  retryInterval: 3m
