apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site
spec:
  commonName: ${local_hostname}
  dnsNames:
    - ${local_hostname}
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  secretName: site-tls
