- op: add
  path: /spec/template/spec/initContainers
  value: []

- op: add
  path: /spec/template/spec/initContainers/0
  value:
    name: trust-cloud-ca
    image: docker.io/grafana/alpine:3.15.4
    command:
      - /bin/sh
      - -c
    args:
      - update-ca-certificates && cp -r /etc/ssl/certs/* /tmp/trust-bundle
    volumeMounts:
      - name: trust-cloud-ca
        mountPath: /usr/local/share/ca-certificates
      - name: trust-bundle
        mountPath: /tmp/trust-bundle
        readOnly: false

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: trust-bundle
    mountPath: /etc/ssl/certs

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: trust-cloud-ca
    configMap:
      name: cloud-ca

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: trust-bundle
    emptyDir: {}
