cluster:
  discovery:
    registries:
      kubernetes:
        disabled: false
      service:
        disabled: true
  controlPlane:
    endpoint: ${public_endpoint}
  controllerManager:
    extraArgs:
      allocate-node-cidrs: true
  apiServer:
    certSANs:
      - ${cmd_hostname}
      - ${cmd_private_ip}
  network:
    cni:
      name: none
    podSubnets:
      - ${pod_cidr}
    serviceSubnets:
      - ${service_cidr}
machine:
  features:
    hostDNS:
      forwardKubeDNSToHost: true
    kubePrism:
      enabled: true
      port: 7445
  certSANs:
    - ${cmd_hostname}
    - ${cmd_private_ip}
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - source: /opt/local-path-provisioner
        destination: /opt/local-path-provisioner
        type: bind
        options:
          - bind
          - rshared
          - rw
    nodeIP:
      validSubnets:
        - ${ctrl_cidr}
        - ${work_cidr}
  network:
    nameservers:
      - ${dns_private_ip}
  time:
    servers:
      - time.cloudflare.com
      - ntp1.net.berkeley.edu
      - pool.ntp.org
