cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445
ipam:
  mode: kubernetes
encryption:
  enabled: true
  type: wireguard
securityContext:
  capabilities:
    ciliumAgent: [CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID]
    cleanCiliumState: [NET_ADMIN,SYS_ADMIN,SYS_RESOURCE]
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
nodePort:
  enabled: true
