apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.21.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
