apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.18
      sourceRef:
        kind: HelmRepository
        name: external-secrets
