apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
spec:
  interval: 5m
  chart:
    spec:
      chart: contour
      version: 18.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    envoy:
      service:
        nodePorts:
          http: 30080
          https: 30443
