apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-ingress
      version: 1.39.4
      sourceRef:
        kind: HelmRepository
        name: haproxytech
  values:
    controller:
      service:
        nodePorts:
          http: 30080
          https: 30443
          stat: 31024
          quic: 30443
      defaultTLSSecret:
        enabled: false
      kind: DaemonSet
