apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    installCRDs: true
    clusterResourceNamespace: config-ingress
    extraArgs:
      - --enable-gateway-api
