apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-tls-ca
spec:
  refreshInterval: 5s
  secretStoreRef:
    kind: ClusterSecretStore
    name: local
  target:
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: /config-ingress/ingress-tls
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: /config-ingress/ingress-tls
        property: tls.key
