apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: local
spec:
  provider:
    webhook:
      url: https://${secrets_hostname}/?key={{ .remoteRef.key }}
      headers:
        Authorization: Basic {{ print "test:test" | b64enc }} # todo: parameterize
      result:
        jsonPath: $[`{{ .remoteRef.property }}`]
      caProvider:
        type: ConfigMap
        name: cloud-ca
        namespace: flux-system
        key: ca.pem
